M48
; DRILL file {KiCad 7.0.2} date Sun May 28 06:01:16 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-28T06:01:16+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X78.09Y-95.365
X78.09Y-100.215
T2
X75.06Y-95.065
X75.06Y-100.515
T0
M30
